DATASET:
    NAME: "cityscape"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    NUM_CLASS: 19
TRAIN:
    EPOCHS: 1000
    BATCH_SIZE: 12
    CROP_SIZE: (512, 1024)
    PRETRAINED_MODEL_PATH: 'runs/checkpoints/FastSCNN__cityscape_BGA/best_model.pth'
TEST:
    BATCH_SIZE: 4
    TEST_MODEL_PATH: 'runs/checkpoints/fast_scnn__cityscape_2019-11-19-02-02/best_model.pth'

SOLVER:
    LR: 0.045
    DECODER_LR_FACTOR: 1.0
    WEIGHT_DECAY: 4e-5
    AUX: True
    AUX_WEIGHT: 0.4

AUG:
    COLOR_JITTER: 0.4

MODEL:
    MODEL_NAME: "FastSCNN"
    BN_MOMENTUM: 0.01
    MODEL_FACTOR: 4

ARCH:
    SEARCHSPACE: 'GeneralizedFastSCNN'
    ENTROPY_REGULARIZATION: True
    ENTROPY_REGULARIZATION_WEIGHT: 10.
    ENTROPY_PERIOD: (0.0, 0.0)
    L1_REGULARIZATION: False
    L1_REGULARIZATION_WEIGHT: 5.
    L1_PERIOD: (0.0, 0.0)
    HARD_ARCH_TRAINING: False
    HARD_WEIGHT_TRAINING: True
    HARD_EVAL: True
    SEARCH_EPOCH: 0
